name: CICD Pipelines

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write    
  

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn compile
      
  security-check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Docker installation
      run: 
        sudo apt update
        sudo apt install -y docker.io
        sudo systemctl start docker
        sudo systemctl enable docker
        docker --version
        sudo systemctl status docker
      
        
    - name: Gitleaks Installation
      run: sudo apt install gitleaks -y

    - name: Gitleaks Code Scan
      run: gitleaks detect source . -r gitleaks-report.json -f json
    
    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    - name: Update dependency graph
      uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
